Repository defenseunicorns/go-oscal, pull requests merged in 2023-12, with the labels that each got.

#59 Feat: update ValidateCommand parameters to allow streamlined export
  src/cmd/validate/validate.go
Labels: enhancement

#71 feat: initial release process
  .github/actions/save-logs/action.yaml
  .github/workflows/release.yml
  .goreleaser.yaml
  docs/release-process.md
Labels: enhancement

#75 fix: CODEOWNER creation and dependabot removal
  .github/dependabot.yml
  CODEOWNERS
Labels: dependencies

#89 fix!: renovate validator to update config
  renovate.json
Labels: bug, dependencies

#103 #102. Create UpdateLastModified method that is used when revising a p…
  src/internal/utils/version.go
  src/internal/utils/version_test.go
Labels: enhancement
